-- =====================================================================
-- 数据库增量迁移脚本：添加学生成长档案 (Student Portfolios) 支持
-- 请直接在 Supabase SQL Editor 中执行此脚本
-- =====================================================================

-- 1. 创建 student_portfolios 表
-- 使用 IF NOT EXISTS 防止重复创建报错
create table if not exists public.student_portfolios (
  id bigint generated by default as identity primary key,
  slug text not null unique, -- 用于生成个性化链接，例如 'jaydenyip'
  student_name text not null,
  access_password text not null, -- 简易访问密码
  content_blocks jsonb default '[]'::jsonb, -- 存储自定义模块（文本、图片集、视频等）
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. 启用行级安全 (RLS)
alter table public.student_portfolios enable row level security;

-- 3. 配置访问策略 (Policies)

-- 3.1 允许所有人读取 (Public Read)
-- 前端需要读取数据来验证密码（虽然密码验证在前端，但需要先获取记录）
-- 先尝试删除旧策略以防命名冲突
drop policy if exists "Allow public read access" on public.student_portfolios;
create policy "Allow public read access" on public.student_portfolios 
for select using (true);

-- 3.2 允许认证用户(管理员) 插入数据
drop policy if exists "Allow authenticated insert" on public.student_portfolios;
create policy "Allow authenticated insert" on public.student_portfolios 
for insert with check (auth.role() = 'authenticated');

-- 3.3 允许认证用户(管理员) 更新数据
drop policy if exists "Allow authenticated update" on public.student_portfolios;
create policy "Allow authenticated update" on public.student_portfolios 
for all using (auth.role() = 'authenticated');

-- 3.4 允许认证用户(管理员) 删除数据
drop policy if exists "Allow authenticated delete" on public.student_portfolios;
create policy "Allow authenticated delete" on public.student_portfolios 
for delete using (auth.role() = 'authenticated');

-- 4. 刷新 Schema 缓存
NOTIFY pgrst, 'reload schema';