-- Run this SQL in your Supabase SQL Editor to set up the tables AND populate initial data

-- ==========================================
-- 0. CLEANUP (Reset Schema)
-- ==========================================
-- CAUTION: This will delete all existing data in these tables!
DROP TABLE IF EXISTS public.curriculum CASCADE;
DROP TABLE IF EXISTS public.philosophy CASCADE;
DROP TABLE IF EXISTS public.showcases CASCADE;
DROP TABLE IF EXISTS public.page_sections CASCADE;

-- ==========================================
-- 1. Create Tables
-- ==========================================

-- 1.1 Create Curriculum Table
create table public.curriculum (
  id text primary key, -- e.g. "L1"
  level text not null,
  age text not null,
  title text not null,
  description text not null,
  skills text[] not null,
  icon_name text not null,
  image_url text, -- Course cover images
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 1.2 Create Philosophy Table
create table public.philosophy (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  icon_name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 1.3 Create Showcases Table
create table public.showcases (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  description text not null,
  image_alt text not null, -- Stores public URL or iframe HTML
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 1.4 Create Page Sections Table
create table public.page_sections (
  id text primary key, -- e.g. "hero", "philosophy", "social_practice"
  title text not null,
  subtitle text,
  description text,
  metadata jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ==========================================
-- 2. Security (RLS)
-- ==========================================

-- Enable Row Level Security
alter table public.curriculum enable row level security;
alter table public.philosophy enable row level security;
alter table public.showcases enable row level security;
alter table public.page_sections enable row level security;

-- Create Policies
-- Read policies (Public)
create policy "Allow public read access" on public.curriculum for select using (true);
create policy "Allow public read access" on public.philosophy for select using (true);
create policy "Allow public read access" on public.showcases for select using (true);
create policy "Allow public read access" on public.page_sections for select using (true);

-- Write policies (Authenticated users only)
create policy "Allow authenticated update" on public.curriculum for all using (auth.role() = 'authenticated');
create policy "Allow authenticated update" on public.philosophy for all using (auth.role() = 'authenticated');
create policy "Allow authenticated update" on public.showcases for all using (auth.role() = 'authenticated');
create policy "Allow authenticated update" on public.page_sections for all using (auth.role() = 'authenticated');

-- ==========================================
-- 3. Insert Initial Data
-- ==========================================

insert into public.page_sections (id, title, subtitle, description, metadata)
values
('hero', '给孩子带得走的', '', '在这个人工智能时代，我们不仅教授编程与硬件，更致力于培养孩子解决复杂问题的工程思维。从激发好奇心到顶尖名校科研背景，为未来做好准备。', '{"highlighted_text": "硬核科技创造力", "cta1": "查看孩子的成长规划", "cta2": "看看学员们做出了什么"}'),
('philosophy', '不仅是兴趣班，更是未来竞争力的孵化器', 'OUR MISSION', '我们用6年时间打磨出一套标准化的“真做”课程，让科技素养成为孩子受益终身的能力。', '{}'),
('curriculum', 'L1-L7 阶梯式成长体系', 'GROWTH PATH', '科学规划7级成长阶梯，匹配孩子不同年龄段的认知发展。从动手启蒙到算法科研，直通顶尖学府。', '{}'),
('showcases', '让孩子的才华被世界看见', 'SUCCESS STORIES', '在创智实验室，没有“死记硬背”的知识。每一个项目都是为了解决真实世界的问题而生，成为孩子简历上最亮眼的勋章。', '{}'),
('social_practice', '让创意的价值\n在真实市场中得到验证', '社会实践与财商启蒙', '我们鼓励孩子将作品产品化。通过将创意转化为开源硬件套件或服务，孩子不仅能获得人生“第一桶金”，更重要的是在这一过程中理解经济运行的规律，培养极其宝贵的企业家精神。', '{"list_items": ["从Idea到产品的全流程体验", "理解成本、定价与市场需求", "提前积累真实的社会实践履历"], "card_title": "学员项目商业化案例", "card_subtitle": "市场验证与价值回馈", "quote": "“这不仅仅是一次售卖，更是孩子建立自信、理解社会价值的最好一课。”", "note": "* 部分优秀学员作品已成功上线创客市场"}'),
('booking', '预约体验课', 'BOOK NOW', '请留下您的联系方式，我们的课程顾问将在24小时内与您联系，为您安排个性化试听体验。', '{"nav_button_text": "预约试听", "mobile_button_text": "预约体验课", "submit_button_text": "立即预约", "success_message": "预约成功！我们会尽快联系您。"}'),
('footer', '联系我们', '', '创智实验室 (SparkMinds) 专注于青少年硬核科技素养教育。\n\n我们致力于为中国家庭提供一条科学、扎实、具有国际视野的科技创新成长路径。', '{"address": "广州/深圳 线下创新中心", "email": "contact@sparkminds.edu", "phone": "400-123-4567", "copyright": "© 2024 SparkMinds 创智实验室. All rights reserved.", "explore_title": "探索", "contact_title": "联系我们"}');


-- ==========================================
-- 4. Storage Bucket Setup
-- ==========================================

-- 1. Create a new storage bucket called 'images'
insert into storage.buckets (id, name, public)
values ('images', 'images', true)
on conflict (id) do nothing;

-- 2. Set up Storage Policies (Drop old ones first to avoid conflicts if needed, but usually policies are tied to tables/buckets)
-- Note: Storage policies are tricky to "reset" without dropping the bucket, but since we are just adding them:

drop policy if exists "Public Access" on storage.objects;
drop policy if exists "Authenticated Upload" on storage.objects;
drop policy if exists "Authenticated Update" on storage.objects;
drop policy if exists "Authenticated Delete" on storage.objects;

-- Allow public access to view images
create policy "Public Access"
on storage.objects for select
using ( bucket_id = 'images' );

-- Allow authenticated users to upload images
create policy "Authenticated Upload"
on storage.objects for insert
with check ( bucket_id = 'images' and auth.role() = 'authenticated' );

-- Allow authenticated users to update images
create policy "Authenticated Update"
on storage.objects for update
using ( bucket_id = 'images' and auth.role() = 'authenticated' );

-- Allow authenticated users to delete images
create policy "Authenticated Delete"
on storage.objects for delete
using ( bucket_id = 'images' and auth.role() = 'authenticated' );