-- Run this SQL in your Supabase SQL Editor to set up the tables AND populate initial data

-- 1. Create Curriculum Table
create table if not exists public.curriculum (
  id text primary key, -- e.g. "L1"
  level text not null,
  age text not null,
  title text not null,
  description text not null,
  skills text[] not null,
  icon_name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create Philosophy Table
create table if not exists public.philosophy (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  icon_name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create Showcases Table
create table if not exists public.showcases (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  description text not null,
  image_alt text not null, -- This will store the public URL from Supabase Storage
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Enable Row Level Security
alter table public.curriculum enable row level security;
alter table public.philosophy enable row level security;
alter table public.showcases enable row level security;

-- 5. Create Policies for Tables
drop policy if exists "Allow public read access" on public.curriculum;
drop policy if exists "Allow public read access" on public.philosophy;
drop policy if exists "Allow public read access" on public.showcases;
drop policy if exists "Allow authenticated update" on public.curriculum;
drop policy if exists "Allow authenticated update" on public.philosophy;
drop policy if exists "Allow authenticated update" on public.showcases;

-- Read policies (Public)
create policy "Allow public read access" on public.curriculum for select using (true);
create policy "Allow public read access" on public.philosophy for select using (true);
create policy "Allow public read access" on public.showcases for select using (true);

-- Write policies (Authenticated users only)
create policy "Allow authenticated update" on public.curriculum for all using (auth.role() = 'authenticated');
create policy "Allow authenticated update" on public.philosophy for all using (auth.role() = 'authenticated');
create policy "Allow authenticated update" on public.showcases for all using (auth.role() = 'authenticated');

-- 6. Insert Initial Data from constants.ts (Existing logic...)
-- ... (Existing INSERT statements omitted for brevity, they remain the same) ...


-- ==========================================
-- NEW: Storage Bucket Setup
-- ==========================================

-- 1. Create a new storage bucket called 'images'
insert into storage.buckets (id, name, public)
values ('images', 'images', true)
on conflict (id) do nothing;

-- 2. Set up Storage Policies

-- Allow public access to view images
create policy "Public Access"
on storage.objects for select
using ( bucket_id = 'images' );

-- Allow authenticated users to upload images
create policy "Authenticated Upload"
on storage.objects for insert
with check ( bucket_id = 'images' and auth.role() = 'authenticated' );

-- Allow authenticated users to update images
create policy "Authenticated Update"
on storage.objects for update
using ( bucket_id = 'images' and auth.role() = 'authenticated' );

-- Allow authenticated users to delete images
create policy "Authenticated Delete"
on storage.objects for delete
using ( bucket_id = 'images' and auth.role() = 'authenticated' );
