
-- Run this SQL in your Supabase SQL Editor to set up the tables AND populate initial data

-- ==========================================
-- 0. CLEANUP (Reset Schema)
-- ==========================================
-- CAUTION: This will delete all existing data in these tables!
-- DROP TABLE IF EXISTS public.curriculum CASCADE;
-- DROP TABLE IF EXISTS public.philosophy CASCADE;
-- DROP TABLE IF EXISTS public.showcases CASCADE;
-- DROP TABLE IF EXISTS public.page_sections CASCADE;
-- DROP TABLE IF EXISTS public.bookings CASCADE;
-- DROP TABLE IF EXISTS public.social_projects CASCADE;
-- DROP TABLE IF EXISTS public.student_portfolios CASCADE;

-- ==========================================
-- 1. Create Tables
-- ==========================================

-- 1.1 Create Curriculum Table
create table if not exists public.curriculum (
  id text primary key, -- e.g. "L1"
  level text not null,
  age text not null,
  title text not null,
  description text not null,
  skills text[] not null,
  icon_name text not null,
  image_urls text[] default '{}',
  sort_order integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 1.2 Create Philosophy Table
create table if not exists public.philosophy (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  icon_name text not null,
  sort_order integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 1.3 Create Showcases Table
create table if not exists public.showcases (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  description text not null,
  image_urls text[] default '{}',
  sort_order integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 1.4 Create Page Sections Table
create table if not exists public.page_sections (
  id text primary key, -- e.g. "hero", "philosophy", "social_practice"
  title text not null,
  subtitle text,
  description text,
  metadata jsonb,
  sort_order integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 1.5 Create Bookings Table
create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  parent_name text not null,
  phone text not null,
  child_age text not null,
  status text default 'pending', -- 'pending' (待处理) or 'contacted' (已联系)
  note text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 1.6 Create Social Projects Table
create table if not exists public.social_projects (
  id bigint generated by default as identity primary key,
  title text not null,
  subtitle text,
  quote text not null,
  footer_note text,
  image_urls text[] default '{}',
  sort_order integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 1.7 Create Student Portfolios Table (New)
create table if not exists public.student_portfolios (
  id bigint generated by default as identity primary key,
  slug text not null unique, -- The URL part, e.g. 'jaydenyip'
  student_name text not null,
  access_password text not null, -- Simple password protection
  content_blocks jsonb default '[]'::jsonb, -- Array of content modules
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ==========================================
-- 2. Security (RLS)
-- ==========================================

-- Enable Row Level Security
alter table public.curriculum enable row level security;
alter table public.philosophy enable row level security;
alter table public.showcases enable row level security;
alter table public.page_sections enable row level security;
alter table public.bookings enable row level security;
alter table public.social_projects enable row level security;
alter table public.student_portfolios enable row level security;

-- Create Policies
-- Read policies (Public)
create policy "Allow public read access" on public.curriculum for select using (true);
create policy "Allow public read access" on public.philosophy for select using (true);
create policy "Allow public read access" on public.showcases for select using (true);
create policy "Allow public read access" on public.page_sections for select using (true);
create policy "Allow public read access" on public.social_projects for select using (true);
create policy "Allow public read access" on public.student_portfolios for select using (true);

-- Write policies (Authenticated users only - Admin)
create policy "Allow authenticated update" on public.curriculum for all using (auth.role() = 'authenticated');
create policy "Allow authenticated update" on public.philosophy for all using (auth.role() = 'authenticated');
create policy "Allow authenticated update" on public.showcases for all using (auth.role() = 'authenticated');
create policy "Allow authenticated update" on public.page_sections for all using (auth.role() = 'authenticated');
create policy "Allow authenticated update" on public.social_projects for all using (auth.role() = 'authenticated');
create policy "Allow authenticated update" on public.student_portfolios for all using (auth.role() = 'authenticated');

-- Also allow inserts for adding new records (Admin)
create policy "Allow authenticated insert" on public.curriculum for insert with check (auth.role() = 'authenticated');
create policy "Allow authenticated insert" on public.philosophy for insert with check (auth.role() = 'authenticated');
create policy "Allow authenticated insert" on public.showcases for insert with check (auth.role() = 'authenticated');
create policy "Allow authenticated insert" on public.page_sections for insert with check (auth.role() = 'authenticated');
create policy "Allow authenticated insert" on public.social_projects for insert with check (auth.role() = 'authenticated');
create policy "Allow authenticated insert" on public.student_portfolios for insert with check (auth.role() = 'authenticated');

-- Allow authenticated delete
create policy "Allow authenticated delete" on public.social_projects for delete using (auth.role() = 'authenticated');
create policy "Allow authenticated delete" on public.showcases for delete using (auth.role() = 'authenticated');
create policy "Allow authenticated delete" on public.curriculum for delete using (auth.role() = 'authenticated');
create policy "Allow authenticated delete" on public.philosophy for delete using (auth.role() = 'authenticated');
create policy "Allow authenticated delete" on public.student_portfolios for delete using (auth.role() = 'authenticated');


-- Bookings Policies
-- 1. Public can INSERT (Submit form)
create policy "Allow public insert bookings" on public.bookings for insert with check (true);
-- 2. Only Authenticated (Admin) can SELECT/UPDATE/DELETE bookings
create policy "Allow admin manage bookings" on public.bookings for all using (auth.role() = 'authenticated');

-- Refresh Schema
NOTIFY pgrst, 'reload schema';
